trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'mohretta/gc-webreact'
  dockerfilePath: 'GC.WebReact/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: Build and push
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    buildContext: '.'
    tags: |
      $(tag)
      tp04-latest