trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'infra'
    artifact: 'infra'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'k8s'
    artifact: 'k8s'
    publishLocation: 'pipeline'