apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-webreact
  namespace: #{ENV}#
  labels:
    app: GC.WebReact
    tier: web

spec:
  replicas: #{REPLICAS}#

  selector:
    matchLabels:
      app: GC.WebReact
      tier: web

  template:
    metadata:
      labels:
        app: GC.WebReact
        tier: web

    spec:
      containers:
        - name: gc-webreact
          image: #{IMAGE}#

          ports:
            - containerPort: 5000

          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5000"

            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: gc-config
                  key: ASPNETCORE_ENVIRONMENT

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: gc-secret
                  key: connectionString